{% set name = "tmtk" %}
{% set version = "0.5.7" %}
{% set sha256 = "1241cabb8f9828f572f3e900f923fcc682a1afdf2f1afb780d4aa4c5454f785e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [py<34]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - transmart-batch = tmtk.utils.batch.__main__:run_batch

requirements:
  build:
    - python
    - pip
    - numpy 1.11.*

  run:
    - python
    - pandas
    - numpy >=1.11
    - tqdm
    - arrow
    - click
    - jupyter
    - xlrd
    - notebook
    - requests
    - ipython
    - widgetsnbextension

test:
  imports:
    - tmtk
    - tmtk.toolbox
    - tmtk.toolbox.skinny_loader
    - tmtk.arborist
    - tmtk.study
    - tmtk.utils
    - tmtk.utils.batch
    - tmtk.clinical
  commands:
    - transmart-batch --help

about:
  home: http://github.com/thehyve/tmtk
  license: LGPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'A toolkit for ETL curation for the tranSMART data warehouse.'

  doc_url: https://tmtk.readthedocs.io/
  dev_url: https://github.com/thehyve/tmtk

extra:
  recipe-maintainers:
    - jochemb
    - spayralbe
    - gijskant
