travis:
  secure:
    BINSTAR_TOKEN: h6z/1n9NcjgfYJ5Stv5I07gxQXnak4VTxxwW5ytThqMYJyiKFbjMjP7ea6RxiuehRIVALNx4Wl54ChdOYmvKdna6Z6Zb3o7nhGut7dvZCHHAcrcDp+jhcWAvYAHUxrgEUHFFk/HzSnAf+yavqyucjuAnRQwBvq32IcA3pZ3oH5eygggwiOUnt0pmLh9kjEF2LA52pSwDvlwLnDrXyVgVg0ya1CnJJVf/xLQ6TZWnaTmcYMbe9jcfyfzu2nJ2gf8ixAvgsN9SDbx7pP7WwJK3Gu5H4Tp71yEvr/4vyhqnyypTjgD4rwUo6/jI3Vm43RfA+g+s0yQ2YiQ7FD1vPv80Fu2bV9MSeqAp5T51g2Wym/9eyOq4e+6Eob/Wx26t9KDXgED5TDASFqM95Za6J+TixRAm+gAYPRHaK4Zk2+ueoBxFDK4NtSae+a0aps2NOhbUonqdp4VaiFxSf7F4U3Zt+qMXIoImG9rRDs2ao9MKQF47loUsWDpPJ0psW0JPT72+Z6Yo/Uw7yIOmD0LgIufvnRwcGj+bFl8A7pPnM4+Fk/Gf0GOdIkqYfGwD688Z851/LiXUQ0Oi/gD0tMeu/VNF6o5N/PZSmiD+VgPp7ibMNmwI0kZYSsQyHt5tMz44DqhSFlsr8s9uAcFVNIFMDAXUKIF02hsIDY5cdhS7ne/M9YA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
