appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: kA7FcRwKMwfvdYCfJdHydk3B6gHvHNH0tMPpXO/B0z1+7EBvgxyHtn6w7PRokYvs2ZGf1qAD8Ue7bSD/FWEDuOt6XoP13wNx1F8WQlqS1fRemodVQc2YLYoJT9Usmt7bamfNYKEy4Ch/QhefpuzjK4ebioEwUdWyU+QrnJ58GzpuHRTY6osSPbVC49ruEwrX5OwB7oD834T8YohfNsd4ZYowBlZDyRfhTka8O6wpLs9+bexCAevLrU25XUItELCA757fenDhvlWqcEtfdqFCdPX/syaizgtGMCXEhCtPIcCemjoge/GZ89bYgooTK49VhIP76VdENprTEAeQQSaXSqcBOqjK2Fa+Kqq4VjNEtlke6xZwJ4Fq8qhXAsl/y+WoVLFrYfGOuOrzmYSw3vyN1FnR8iywZdNcPNe4+KGMy8qT7/vKPm5fSkf31FtHvlXzvmvbKfpdeUP5Sq5axbkpRQaVow7CsqF/sFlobBoLoTnnk9pwCj1GM4FXCpIbInnBV7apaHWhClkGrNM0Ygya63Zpahvaj+WKTcJrQPV3Xr7lX6iLmki29ryrRV1B9EWweU1vKVolevl8VnCIlWNPe9r7ny3vZQJl5xvDoNikwL0FVwB7PaZrBNtOF5vwrLn5jr9Eu35C4uJWfm6HgLQNHDk/ZxYbK4kJGHDgbhKhLoU=}
provider:
  win: azure
