travis:
  secure:
    BINSTAR_TOKEN: pTp0Icaw7JZymyNQpD4xFdLtst30guzV76Hr4wPTrx2M6fHRklq8U7/3aVhMIqqIsdb1XvHXkAOY/6DjadlO5GjpvlADmWSjA40VybMF2AyrjHam/ljRW1AynHWPdAwgMHQwOnqMf+trtZrv4LG5xQHvthUxFCpEPgO8qbNIzuwK4mhD2C98M/nxqUHRJQGGyj5WkgZfnNVJ1Uv5cq5eb5t2KUTqvsh4gfG1UmlGAVaVmPJ6Nmnh4DpI4RMj0wJtS68oqvYXvumciKzzUBzVdtE/FnPIiSTcEBjKc8FPzXzbQdtLCe4TGAXy/DA8LmaqNvhhZL77AmjqLlUVEcdLHubCMcVF83C4sxxD9rUPPrhzR+tfOsBTr24oxmLlqTuGYO2l7/vsZxzH5cqFB0H+cpehEYznwo1SvEvnoXQAL1XqAO4j0m4Sq6zfYHy7178n+++/lLGhUTE00m48KETckco0RrVOO4tZHsC997Ry6MP7UsuWFfwiOHmf6tVo5gpxp3Fr8DfkY9Kb5PtVyo4DUf4kU1ZU2MjW5BFhGErrlG6OVfjoh4sDLL16D3IL2q7z4kNLbcuLgfl1YL02g2ToYN/MtThYb8/Zxbg6uBoNHWKFwCkaiDElKukYsHrP7Lt9gW/9Y0/9IUAr/MNlKu0mxj66qnVLe1EcPHxf+TnF8xA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
